/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "string_check.check" instead.
 */

#include <check.h>

#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include "s21_string.h"
#include <limits.h>



START_TEST(strchr_1) {
char s1[]= "hello world";
ck_assert_str_eq(strchr(s1, 'h'),  s21_strchr(s1, 'h'));
}
END_TEST

START_TEST(strchr_2) {
char s1[]= "hello world";
ck_assert_str_eq(strchr(s1, 108), s21_strchr(s1, 108));
}
END_TEST

START_TEST(strchr_3) {
char s1[]= "hello\0HELL0";
ck_assert_str_eq(strchr(s1, '\0'), s21_strchr(s1, '\0'));
}
END_TEST

START_TEST(strchr_4) {
char s1[]= "AAAA\0ABBBBBCCCCC";
ck_assert_ptr_null(s21_strchr(s1, 11));
}
END_TEST

START_TEST(strchr_5) {
char s1[]= "\nffffooo";
ck_assert_str_eq(strchr(s1, 111), s21_strchr(s1, 111));
}
END_TEST

START_TEST(strlen_1) {
char s1[]= "hello world";
ck_assert_int_eq(strlen(s1), s21_strlen(s1));
}
END_TEST

START_TEST(strlen_2) {
char s1[]= "h123445673542djsnfeasfdhsgthdgsffgdsfghgsdfx`zbnmj, kjhfdgfsdadsfsgdhjkgfjghfg-43fa";
ck_assert_int_eq(strlen(s1), s21_strlen(s1));
}
END_TEST

START_TEST(strlen_3) {
char s1[]= "\n";
ck_assert_int_eq(strlen(s1), s21_strlen(s1));
}
END_TEST

START_TEST(strlen_4) {
char s1[]= "\n\0";
ck_assert_int_eq(strlen(s1), s21_strlen(s1));
}
END_TEST

START_TEST(strlen_5) {
char s1[]= "  \0";
ck_assert_int_eq(strlen(s1), s21_strlen(s1));
}
END_TEST

START_TEST(strlen_6) {
char s1[]= "h\n\0";
ck_assert_int_eq(strlen(s1), s21_strlen(s1));
}
END_TEST

START_TEST(memchr_1) {
char s1[100]= "Hello21school";
ck_assert_pstr_eq(memchr(s1,  'o',  6), s21_memchr(s1,  'o',  6));
}
END_TEST

START_TEST(memchr_2) {
char s1[100]= "Hello 21 school";
ck_assert_pstr_eq(memchr(s1,  111,  14), s21_memchr(s1,  111,  14));
}
END_TEST

START_TEST(memchr_3) {
char s1[100]= "Hello 21 school";
ck_assert_pstr_eq(memchr(s1,  117,  20), s21_memchr(s1,  117,  20));
}
END_TEST

START_TEST(memchr_4) {
char s1[100]= "Hellllll\0school";
ck_assert_pstr_eq(memchr(s1,  117,  20), s21_memchr(s1,  117,  20));
}
END_TEST

START_TEST(memchr_5) {
char s1[100]= "\0school";
ck_assert_pstr_eq(memchr(s1,  115,  20), s21_memchr(s1,  115,  20));
}
END_TEST

START_TEST(memchr_6) {
char s1[100]= "\n\0school";
ck_assert_pstr_eq(memchr(s1,  115,  20), s21_memchr(s1,  115,  20));
}
END_TEST

START_TEST(memcmp_1) {
char s1[]= "Hello21school";
char s2[]= "Hello21school";
char s3[]= "Hello21school";
int res1 = memcmp(s1,  s2,  14);
int res2 = s21_memcmp(s3,  s2,  14);
if (res1 > 0 && res2 > 0) {
    res1 = 1;
    res2 = 1;
} else if (res1 < 0 && res2 < 0) {
    res1 = -1;
    res2 = -1;
}
ck_assert_int_eq(res1,  res2);
}
END_TEST

START_TEST(memcmp_2) {
char s1[]= "Helo21school";
char s2[]= "Hello21school";
int res1 = memcmp(s1,  s2,  5);
int res2 = s21_memcmp(s1,  s2,  5);
if (res1 > 0 && res2 > 0) {
    res1 = 1;
    res2 = 1;
} else if (res1 < 0 && res2 < 0) {
    res1 = -1;
    res2 = -1;
}
ck_assert_int_eq(res1,  res2);
}
END_TEST

START_TEST(memcmp_3) {
char s1[15]= "Hello21school";
char s2[15]= "g ";
int res1 = memcmp(s1,  s2,  12);
int res2 = s21_memcmp(s1,  s2,  12);
if (res1 > 0 && res2 > 0) {
    res1 = 1;
    res2 = 1;
} else if (res1 < 0 && res2 < 0) {
    res1 = -1;
    res2 = -1;
}
ck_assert_int_eq(res1,  res2);
}
END_TEST

START_TEST(memcmp_4) {
char s1[15]= "Hello\021school";
char s2[15]= "\0";
int res1 = memcmp(s1,  s2,  6);
int res2 = s21_memcmp(s1,  s2,  6);
if (res1 > 0 && res2 > 0) {
    res1 = 1;
    res2 = 1;
} else if (res1 < 0 && res2 < 0) {
    res1 = -1;
    res2 = -1;
}
ck_assert_int_eq(res1,  res2);
}
END_TEST

START_TEST(memcmp_5) {
char s1[15]= "Hello\n\021school";
char s2[15]= "\0";
int res1 = memcmp(s1,  s2,  6);
int res2 = s21_memcmp(s1,  s2,  6);
if (res1 > 0 && res2 > 0) {
    res1 = 1;
    res2 = 1;
} else if (res1 < 0 && res2 < 0) {
    res1 = -1;
    res2 = -1;
}
ck_assert_int_eq(res1,  res2);
}
END_TEST

START_TEST(memcmp_6) {
char s1[15]= "Hello\n\021school";
char s2[15]= "e\0";
int res1 = memcmp(s1,  s2,  2);
int res2 = s21_memcmp(s1,  s2,  2);
if (res1 > 0 && res2 > 0) {
    res1 = 1;
    res2 = 1;
} else if (res1 < 0 && res2 < 0) {
    res1 = -1;
    res2 = -1;
}
ck_assert_int_eq(res1,  res2);
}
END_TEST

START_TEST(strcat_1) {
char s1[100]= "Hello ";
char s2[]= "21school";
ck_assert_str_eq(strcat(s1,  s2),  s21_strcat(s1,  s2));
}
END_TEST

START_TEST(strcat_2) {
char s1[100]= "12345";
char s2[]= "   ";
ck_assert_str_eq(strcat(s1,  s2),  s21_strcat(s1,  s2));
}
END_TEST

START_TEST(strcat_3) {
char s1[]= "Hi";
char s2[]= "";
ck_assert_str_eq(strcat(s1,  s2),  s21_strcat(s1,  s2));
}
END_TEST

START_TEST(strcat_4) {
char s1[100]= "Hi";
char s2[]= "\n\0";
ck_assert_str_eq(strcat(s1,  s2),  s21_strcat(s1,  s2));
}
END_TEST

START_TEST(strcat_5) {
char s1[100]= "\nHi\n";
char s2[]= "\n\0";
ck_assert_str_eq(strcat(s1,  s2),  s21_strcat(s1,  s2));
}
END_TEST

START_TEST(strcat_6) {
char s1[100]= "\nHiiiiiiiiiiiiiii\n";
char s2[]= "\n\0";
ck_assert_str_eq(strcat(s1,  s2),  s21_strcat(s1,  s2));
}
END_TEST

START_TEST(strcmp_1) {
char s1[6]= "Hello";
char s2[6]= "Hello";
int res1 = strcmp(s1,  s2);
int res2 = s21_strcmp(s1,  s2);
if (res1 > 0 && res2 > 0) {
    res1 = 1;
    res2 = 1;
} else if (res1 < 0 && res2 < 0) {
    res1 = -1;
    res2 = -1;
}
ck_assert_int_eq(res1,  res2);
}
END_TEST

START_TEST(strcmp_2) {
char s1[]= "Hello";
char s2[]= "Helo";
int res1 = strcmp(s1,  s2);
int res2 = s21_strcmp(s1,  s2);
if (res1 > 0 && res2 > 0) {
    res1 = 1;
    res2 = 1;
} else if (res1 < 0 && res2 < 0) {
    res1 = -1;
    res2 = -1;
}
ck_assert_int_eq(res1,  res2);
}
END_TEST

START_TEST(strcmp_3) {
char s1[]= "Hello";
char s2[]= "";
int res1 = strcmp(s1,  s2);
int res2 = s21_strcmp(s1,  s2);
if (res1 > 0 && res2 > 0) {
    res1 = 1;
    res2 = 1;
} else if (res1 < 0 && res2 < 0) {
    res1 = -1;
    res2 = -1;
}
ck_assert_int_eq(res1,  res2);
}
END_TEST

START_TEST(strcmp_4) {
char s1[]= "Hello";
char s2[]= "Hello\0";
int res1 = strcmp(s1,  s2);
int res2 = s21_strcmp(s1,  s2);
if (res1 > 0 && res2 > 0) {
    res1 = 1;
    res2 = 1;
} else if (res1 < 0 && res2 < 0) {
    res1 = -1;
    res2 = -1;
}
ck_assert_int_eq(res1,  res2);
}
END_TEST

START_TEST(strcmp_5) {
char s1[]= "Hello\0";
char s2[]= "Hello\0";
int res1 = strcmp(s1,  s2);
int res2 = s21_strcmp(s1,  s2);
if (res1 > 0 && res2 > 0) {
    res1 = 1;
    res2 = 1;
} else if (res1 < 0 && res2 < 0) {
    res1 = -1;
    res2 = -1;
}
ck_assert_int_eq(res1,  res2);
}
END_TEST

START_TEST(strcmp_6) {
char s1[]= "lllllo\0";
char s2[]= "lllllo\n\0";
int res1 = strcmp(s1,  s2);
int res2 = s21_strcmp(s1,  s2);
if (res1 > 0 && res2 > 0) {
    res1 = 1;
    res2 = 1;
} else if (res1 < 0 && res2 < 0) {
    res1 = -1;
    res2 = -1;
}
ck_assert_int_eq(res1,  res2);
}
END_TEST

START_TEST(strncmp_1) {
char s1[]= "Hello";
char s2[]= "Hello";
int res1 = strncmp(s1,  s2,  5);
int res2 = s21_strncmp(s1,  s2,  5);
if (res1 > 0 && res2 > 0) {
    res1 = 1;
    res2 = 1;
} else if (res1 < 0 && res2 < 0) {
    res1 = -1;
    res2 = -1;
}
ck_assert_int_eq(res1,  res2);
}
END_TEST

START_TEST(strncmp_2) {
char s1[]= "HeLllo";
char s2[]= "Hello";
int res1 = strncmp(s1,  s2,  3);
int res2 = s21_strncmp(s1,  s2,  3);
if (res1 > 0 && res2 > 0) {
    res1 = 1;
    res2 = 1;
} else if (res1 < 0 && res2 < 0) {
    res1 = -1;
    res2 = -1;
}
ck_assert_int_eq(res1,  res2);
}
END_TEST

START_TEST(strncmp_3) {
char s1[]= "HeLllo";
char s2[]= "23456";
int res1 = strncmp(s1,  s2,  5);
int res2 = s21_strncmp(s1,  s2,  5);
if (res1 > 0 && res2 > 0) {
    res1 = 1;
    res2 = 1;
} else if (res1 < 0 && res2 < 0) {
    res1 = -1;
    res2 = -1;
}
ck_assert_int_eq(res1,  res2);
}
END_TEST

START_TEST(strncmp_4) {
char s1[]= "Hello";
char s2[]= "Hello\0";
int res1 = strncmp(s1,  s2,  6);
int res2 = s21_strncmp(s1,  s2,  6);
if (res1 > 0 && res2 > 0) {
    res1 = 1;
    res2 = 1;
} else if (res1 < 0 && res2 < 0) {
    res1 = -1;
    res2 = -1;
}
ck_assert_int_eq(res1,  res2);
}
END_TEST

START_TEST(strncmp_5) {
char s1[]= "Hello\0";
char s2[]= "Hello\0";
int res1 = strncmp(s1,  s2,  7);
int res2 = s21_strncmp(s1,  s2,  7);
if (res1 > 0 && res2 > 0) {
    res1 = 1;
    res2 = 1;
} else if (res1 < 0 && res2 < 0) {
    res1 = -1;
    res2 = -1;
}
ck_assert_int_eq(res1,  res2);
}
END_TEST

START_TEST(strncat_1) {
char s1[100]= "Hello ";
char s2[]= "21school";
ck_assert_str_eq(strncat(s1,  s2,  5),  s21_strncat(s1,  s2,  5));
}
END_TEST

START_TEST(strncat_2) {
char s1[100]= "HoHoHo";
char s2[]= "21";
ck_assert_str_eq(strncat(s1,  s2,  2),  s21_strncat(s1,  s2,  2));
}
END_TEST

START_TEST(strncat_3) {
char s1[100]= "Whats up";
char s2[]= "";
ck_assert_str_eq(strncat(s1,  s2,  3),  s21_strncat(s1,  s2,  3));
}
END_TEST

START_TEST(strncat_4) {
char s1[100]= "Whatswup";
char s2[]= "\n\n\0";
ck_assert_str_eq(strncat(s1,  s2,  10),  s21_strncat(s1,  s2,  10));
}
END_TEST

START_TEST(strspn_1) {
char s1[]= "Hello";
char s2[]= "Hel";
ck_assert_int_eq(strspn(s1,  s2),  s21_strspn(s1,  s2));
}
END_TEST

START_TEST(strspn_2) {
char s1[]= "Hello";
char s2[]= "A7";
ck_assert_int_eq(strspn(s1,  s2),  s21_strspn(s1,  s2));
}
END_TEST

START_TEST(strspn_3) {
char s1[]= "Hello";
char s2[]= "";
ck_assert_int_eq(strspn(s1,  s2),  s21_strspn(s1,  s2));
}
END_TEST

START_TEST(strspn_4) {
char s1[]= "Hello";
char s2[]= "\0";
ck_assert_int_eq(strspn(s1,  s2),  s21_strspn(s1,  s2));
}
END_TEST

START_TEST(strstr_1) {
char s1[]= "Hello";
char s2[]= "He";
ck_assert_str_eq(strstr(s1,  s2),  s21_strstr(s1,  s2));
}
END_TEST

START_TEST(strstr_2) {
char s1[]= "HelloHelllo";
char s2[]= "l";
ck_assert_str_eq(strstr(s1,  s2),  s21_strstr(s1,  s2));
}
END_TEST

START_TEST(strstr_3) {
char s1[]= "HelloWorld";
char s2[]= "W";
ck_assert_str_eq(strstr(s1,  s2),  s21_strstr(s1,  s2));
}
END_TEST

START_TEST(strstr_4) {
char s1[]= "HelloWorld";
char s2[]= "";
ck_assert_str_eq(strstr(s1,  s2),  s21_strstr(s1,  s2));
}
END_TEST

START_TEST(strstr_5) {
char s1[]= "";
char s2[]= "d";
ck_assert_ptr_null(s21_strstr(s1,  s2));
}
END_TEST

START_TEST(strrchr_1) {
char s1[100]= "Hello";
ck_assert_str_eq(strrchr(s1,  108),  s21_strrchr(s1,  108));
}
END_TEST

START_TEST(strrchr_2) {
char s1[100]= "HelloWorld0000";
ck_assert_str_eq(strrchr(s1,  48),  s21_strrchr(s1,  48));
}
END_TEST

START_TEST(strrchr_3) {
char s1[100]= "ReadyTo";
ck_assert_ptr_null(s21_strrchr(s1,  38));
}
END_TEST

START_TEST(strcpy_1) {
char s1[100]= "Hello";
char s2[100]= "World";
ck_assert_str_eq(strcpy(s1,  s2),  s21_strcpy(s1,  s2));
}
END_TEST

START_TEST(strcpy_2) {
char s1[100]= "Hello";
char s2[]= "WorldHELLOWORLD";
ck_assert_str_eq(strcpy(s1,  s2),  s21_strcpy(s1,  s2));
}
END_TEST

START_TEST(strcpy_3) {
char s1[8]= "   ";
char s2[3]= "!\0";
ck_assert_str_eq(strcpy(s1,  s2),  s21_strcpy(s1,  s2));
}
END_TEST

START_TEST(strncpy_1) {
char s1[100]= "Hello";
char s2[100]= "World";
ck_assert_str_eq(strncpy(s1,  s2,  3),  s21_strncpy(s1,  s2,  3));
}
END_TEST

START_TEST(strncpy_2) {
char s1[100]= "Hello()";
char s2[100]= "!!!";
ck_assert_str_eq(strncpy(s1,  s2,  10),  s21_strncpy(s1,  s2,  10));
}
END_TEST

START_TEST(strncpy_3) {
char s1[100]= "WORLD";
char s2[100]= "";
ck_assert_str_eq(strncpy(s1,  s2,  5),  s21_strncpy(s1,  s2,  5));
}
END_TEST

START_TEST(strncpy_4) {
char s1[100]= "\n";
char s2[100]= "\n\0";
ck_assert_str_eq(strncpy(s1,  s2,  5),  s21_strncpy(s1,  s2,  5));
}
END_TEST

START_TEST(strpbrk_1) {
char s1[100]= "Hello";
char s2[100]= "eo";
ck_assert_str_eq(strpbrk(s1,  s2),  s21_strpbrk(s1,  s2));
}
END_TEST

START_TEST(strpbrk_2) {
char s1[100]= "HelloWorld1234567890";
char s2[100]= "03";
ck_assert_str_eq(strpbrk(s1,  s2),  s21_strpbrk(s1,  s2));
}
END_TEST

START_TEST(strpbrk_3) {
char s1[100]= "HelloWorld1234567890";
char s2[100]= "";
ck_assert_ptr_null(s21_strpbrk(s1,  s2));
}
END_TEST

START_TEST(strpbrk_4) {
char s1[100]= "HelloWorld1234567890";
char s2[100]= "\n\00";
ck_assert_ptr_null(s21_strpbrk(s1,  s2));
}
END_TEST

START_TEST(memset_1) {
char s1[100]= "Hello";
ck_assert_str_eq(memset(s1,  100,  4),  s21_memset(s1,  100,  4));
}
END_TEST

START_TEST(memset_2) {
char s1[100]= "WWWWWWKKKK\0KKKCCCCC";
ck_assert_pstr_eq(memset(s1,  74,  4),  s21_memset(s1,  74,  4));
}
END_TEST

START_TEST(memset_3) {
char s1[100]= "";
ck_assert_pstr_eq(memset(s1,  87,  4),  s21_memset(s1,  87,  4));
}
END_TEST

START_TEST(memset_4) {
char s1[100]= "";
ck_assert_pstr_eq(memset(s1,  87,  4),  s21_memset(s1,  87,  4));
}
END_TEST

START_TEST(memcpy_1) {
char s1[100]= "WorldHELLOWORLD";
char s3[100]= "WorldHELLOWORLD";
char s2[100]= "AAABBB";
ck_assert_pstr_eq(memcpy(s1,  s2,  8),  s21_memcpy(s3,  s2,  8));
}
END_TEST

START_TEST(memcpy_2) {
char s1[100]= "AAA";
char s3[100]= "AAA";
char s2[100]= "!!!";
ck_assert_pstr_eq(memcpy(s1,  s2,  4),  s21_memcpy(s3,  s2,  4));
}
END_TEST

START_TEST(memcpy_3) {
char s1[100]= "AAA";
char s3[100]= "AAA";
char s2[100]= "!!!!!qqqSS";
ck_assert_pstr_eq(memcpy(s1,  s2,  10),  s21_memcpy(s3,  s2,  10));
}
END_TEST

START_TEST(memcpy_4) {
char s1[100]= "AAA";
char s3[100]= "AAA";
char s2[100]= "!!!!!qq\0qSS";
ck_assert_pstr_eq(memcpy(s1,  s2,  10),  s21_memcpy(s3,  s2,  10));
}
END_TEST

START_TEST(memmove_1) {
char s1[100]= "Hello21school";
char s2[100]= "ABCDE";
ck_assert_pstr_eq(memmove(s1,  s2,  5),  s21_memmove(s1,  s2,  5));
}
END_TEST

START_TEST(memmove_2) {
char s1[100]= "Hello21school";
char s2[100]= "HelloWorld0000";
ck_assert_pstr_eq(memmove(s1,  s2,  3),  s21_memmove(s1,  s2,  3));
}
END_TEST

START_TEST(memmove_3) {
char s1[15]= "Hello21school";
char s2[100]= "AAAAA\nBBBBBCCCCC";
ck_assert_pstr_eq(memmove(s1,  s2,  13),  s21_memmove(s1,  s2,  13));
}
END_TEST

START_TEST(memmove_4) {
char s1[15]= "Hello21school";
char s2[100]= "AAAAABBBBBCCCCC";
ck_assert_pstr_eq(memmove(s1,  s2,  13),  s21_memmove(s1,  s2,  13));
}
END_TEST

START_TEST(memmove_5) {
char s1[15]= "Hello";
char s2[100]= "AAAAABBBBB";
ck_assert_pstr_eq(memmove(s1,  s2,  13),  s21_memmove(s1,  s2,  13));
}
END_TEST

START_TEST(memmove_6) {
char s1[15]= "AAA";
char s2[100]= "AAAAABBBBB";
ck_assert_pstr_eq(memmove(s1,  s2,  2),  s21_memmove(s1,  s2,  2));
}
END_TEST

START_TEST(memmove_7) {
char s1[15]= "AAAAABBBBB";
char s2[100]= "AAAAABBBBB";
ck_assert_pstr_eq(memmove(s1,  s2,  10),  s21_memmove(s1,  s2,  10));
}
END_TEST

START_TEST(strtok_1) {
char s1[100]= "Hello 21 school";
char s2[100]= " ";
ck_assert_pstr_eq(strtok(s1,  s2),  s21_strtok(s1,  s2));
}
END_TEST

START_TEST(strtok_2) {
char s1[100]= " *Hello 21 *school";
char s2[100]= " *";
ck_assert_pstr_eq(strtok(s1,  s2),  s21_strtok(s1,  s2));
}
END_TEST

START_TEST(strtok_3) {
char s1[100]= " Hello 21 school";
char s2[100]= "*:";
ck_assert_pstr_eq(strtok(s1,  s2),  s21_strtok(s1,  s2));
}
END_TEST

START_TEST(strtok_4) {
char s1[100]= " *******Hello 21      ******scho   ol ";
char s2[100]= "*:";
ck_assert_pstr_eq(strtok(s1,  s2),  s21_strtok(s1,  s2));
}
END_TEST

START_TEST(strtok_6) {
char s1[100]={0};
char s2[100]= " ";
ck_assert_pstr_eq(strtok(s1,  s2),  s21_strtok(s1,  s2));
}
END_TEST

START_TEST(strtok_7) {
char *s1 = "***";
char s2[100]= "***";
ck_assert_pstr_eq(strtok(s1,  s2),  s21_strtok(s1,  s2));
}
END_TEST

START_TEST(strtok_8) {
char s1[100]="%%%%HHH";
char s2[100]= "%%%%";
ck_assert_pstr_eq(strtok(s1,  s2),  s21_strtok(s1,  s2));
}
END_TEST

START_TEST(strtok_9) {
char s1[100]="Aa Aa Aa H Aa";
char s2[100]= "H ";
ck_assert_pstr_eq(strtok(s1,  s2),  s21_strtok(s1,  s2));
}
END_TEST

START_TEST(strcspn_1) {
char s1[]= "hello world";
char s2[]= "helfgbgf";
ck_assert_int_eq(strcspn(s1,  s2), s21_strcspn(s1,  s2));
}
END_TEST

START_TEST(strcspn_2) {
char s1[]= "ee\0";
char s2[]= "faa";
ck_assert_int_eq(strcspn(s1,  s2), s21_strcspn(s1,  s2));
}
END_TEST

START_TEST(strcspn_3) {
char s1[]= "ee\0";
char s2[]= "\0";
ck_assert_int_eq(strcspn(s1,  s2), s21_strcspn(s1,  s2));
}
END_TEST

START_TEST(strcspn_4) {
char s1[100]= "";
char s2[100]= "\0";
ck_assert_int_eq(strcspn(s1,  s2), s21_strcspn(s1,  s2));
}
END_TEST

START_TEST(strerror_1) {
ck_assert_str_eq(strerror(12), s21_strerror(12));
}
END_TEST

START_TEST(strerror_2) {
ck_assert_str_eq(strerror(300), s21_strerror(300));
}
END_TEST

START_TEST(strerror_3) {
ck_assert_str_eq(strerror(0), s21_strerror(0));
}
END_TEST

START_TEST(sprintf_c_1) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%1c %c",  'H',  'z');
s21_sprintf(s2,  "%1c %c",  'H',  'z');
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_c_2) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%10c %2c",  'H',  'z');
s21_sprintf(s2,  "%10c %2c",  'H',  'z');
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_c_3) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%-1c %-c",  'H',  'z');
s21_sprintf(s2,  "%-1c %-c",  'H',  'z');
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_c_4) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%cello",  'h');
s21_sprintf(s2,  "%cello",  'h');
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_c_5) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "LL %c",  'h');
s21_sprintf(s2,  "LL %c",  'h');
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_c_6) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "LL %c:%c,  %d",  'h',  'n',  9);
s21_sprintf(s2,  "LL %c:%c,  %d",  'h',  'n',  9);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_c_7) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%4cello",  'h');
s21_sprintf(s2,  "%4cello",  'h');
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_c_8) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%3cel%s",  'h',  "lo");
s21_sprintf(s2,  "%3cel%s",  'h',  "lo");
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_c_9) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%-3cel%.5s",  'h',  "lolololo");
s21_sprintf(s2,  "%-3cel%.5s",  'h',  "lolololo");
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_c_10) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%3c",  'h');
s21_sprintf(s2,  "%3c",  'h');
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_d_1) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%d%%\n",  4);
s21_sprintf(s2,  "%d%%\n",  4);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_d_2) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%d%%\n",  4);
s21_sprintf(s2,  "%d%%\n",  4);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_d_3) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%d%%\n",  -4);
s21_sprintf(s2,  "%d%%\n",  -4);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_d_4) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "max %d",  INT_MAX);
s21_sprintf(s2,  "max %d",  INT_MAX);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_d_5) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "min %d",  INT_MIN);
s21_sprintf(s2,  "min %d",  INT_MIN);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_d_6) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "Allo %d.%d%d",  8,  8,  0);
s21_sprintf(s2,  "Allo %d.%d%d",  8,  8,  0);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_d_7) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "Allo %d.%d%d, ,  %s",  8,  8,  0,  "kek");
s21_sprintf(s2,  "Allo %d.%d%d, ,  %s",  8,  8,  0,  "kek");
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_d_8) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%4d'",  9);
s21_sprintf(s2,  "HHH '%4d'",  9);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_d_9) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%4d'",  -21474836);
s21_sprintf(s2,  "HHH '%4d'",  -21474836);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_d_10) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%4d'",  INT_MIN);
s21_sprintf(s2,  "HHH '%4d'",  INT_MIN);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_d_12) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%.20d'",  2147483647);
s21_sprintf(s2,  "HHH '%.20d'",  2147483647);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_d_13) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%.20d'",  -2147483647 - 1);
s21_sprintf(s2,  "HHH '%.20d'",  -2147483647 - 1);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_d_14) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%-7d'",  11);
s21_sprintf(s2,  "HHH '%-7d'",  11);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_d_15) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%-15d'",  INT_MAX);
s21_sprintf(s2,  "HHH '%-15d'",  INT_MAX);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_d_16) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%-15d'",  INT_MIN);
s21_sprintf(s2,  "HHH '%-15d'",  INT_MIN);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_d_17) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%4.2d'",  93);
s21_sprintf(s2,  "HHH '%4.2d'",  93);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_d_18) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%4.2d'",  INT_MAX);
s21_sprintf(s2,  "HHH '%4.2d'",  INT_MAX);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_d_19) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%4.2ld'",  -2147483648);
s21_sprintf(s2,  "HHH '%4.2ld'",  -2147483648);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_d_20) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%-4.1d'",  29);
s21_sprintf(s2,  "HHH '%-4.1d'",  29);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_d_21) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%-4.1d'",  INT_MAX);
s21_sprintf(s2,  "HHH '%-4.1d'",  INT_MAX);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_d_22) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%ld'",  -2147483648);
s21_sprintf(s2,  "HHH '%ld'",  -2147483648);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_d_23) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%+4.3d'",  84);
s21_sprintf(s2,  "HHH '%+4.3d'",  84);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_d_24) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%+4.3d'",  INT_MAX);
s21_sprintf(s2,  "HHH '%+4.3d'",  INT_MAX);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_d_25) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%+4.3d'",  INT_MIN);
s21_sprintf(s2,  "HHH '%+4.3d'",  INT_MIN);
ck_assert_str_eq(s1,  s2);
}
END_TEST


START_TEST(sprintf_d_26) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '% 10d'",  -23);
s21_sprintf(s2,  "HHH '% 10d'",  -23);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_d_27) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%+4.3d'",  INT_MIN);
s21_sprintf(s2,  "HHH '%+4.3d'",  INT_MIN);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_d_28) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '% d'",  543);
s21_sprintf(s2,  "HHH '% d'",  543);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_d_29) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%+ d'",  543);
s21_sprintf(s2,  "HHH '%+ d'",  543);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_d_30) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%+ d'",  -543);
s21_sprintf(s2,  "HHH '%+ d'",  -543);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_d_31) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%50d'",  -543);
s21_sprintf(s2,  "HHH '%50d'",  -543);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_d_32) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%.0d'",  0);
s21_sprintf(s2,  "HHH '%.0d'",  0);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_d_33) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%+ 5d'",  -56);
s21_sprintf(s2,  "HHH '%+ 5d'",  -56);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_d_34) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '% +-5d'",  56);
s21_sprintf(s2,  "HHH '% +-5d'",  56);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_proc) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%%'");
s21_sprintf(s2,  "HHH '%%'");
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_f_1) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%f",  100000.4);
s21_sprintf(s2,  "%f",  100000.4);
ck_assert_str_eq(s1,  s2);
}
END_TEST


START_TEST(sprintf_f_2) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%0f",  100000.4);
s21_sprintf(s2,  "%0f",  100000.4);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_f_3) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%-20f",  100000.4);
s21_sprintf(s2,  "%-20f",  100000.4);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_f_4) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%f",  555.7777);
s21_sprintf(s2,  "%f",  555.7777);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_f_5) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%0.2f",  555.7777);
s21_sprintf(s2,  "%0.2f",  555.7777);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_f_6) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%+8.6f",  555.7777);
s21_sprintf(s2,  "%+8.6f",  555.7777);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_f_7) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%+8.6f",  -0.7);
s21_sprintf(s2,  "%+8.6f",  -0.7);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_f_8) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%8.3f",  555.7777);
s21_sprintf(s2,  "%8.3f",  555.7777);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_f_9) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%.0lf",  -555.7777);
s21_sprintf(s2,  "%.0f",  -555.7777);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_f_10) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%10.0f",  -555.7777);
s21_sprintf(s2,  "%10.0f",  -555.7777);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_f_11) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%-10.0f",  555.7777);
s21_sprintf(s2,  "%-10.0f",  555.7777);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_f_12) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%-1.0f",  555.7777);
s21_sprintf(s2,  "%-1.0f",  555.7777);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_f_13) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%1.0f",  555.7777);
s21_sprintf(s2,  "%1.0f",  555.7777);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_f_14) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%+1.9f",  -555.7777);
s21_sprintf(s2,  "%+1.9f",  -555.7777);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_f_15) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "% 15f",  -555.7777);
s21_sprintf(s2,  "% 15f",  -555.7777);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_f_16) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%-1.0f",  1.11);
s21_sprintf(s2,  "%-1.0f",  1.11);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_f_17) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%1.0f",  0.1);
s21_sprintf(s2,  "%1.0f",  0.1);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_f_18) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%+1.9f",  -0.1);
s21_sprintf(s2,  "%+1.9f",  -0.1);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_f_19) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%-1.0f",  1.0);
s21_sprintf(s2,  "%-1.0f",  1.0);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_f_20) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%1.0f",  1.0);
s21_sprintf(s2,  "%1.0f",  1.0);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_f_21) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%+1.9f",  -1.0);
s21_sprintf(s2,  "%+1.9f",  -1.0);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_f_22) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%015f",  555.7777);
s21_sprintf(s2,  "%015f",  555.7777);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_f_23) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%05.0f",  555.7777);
s21_sprintf(s2,  "%05.0f",  555.7777);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_f_24) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%+08.06f",  555.7777);
s21_sprintf(s2,  "%+08.06f",  555.7777);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_f_25) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%08.3f",  555.7);
s21_sprintf(s2,  "%08.3f",  555.7);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_f_26) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%08.3f",  5.);
s21_sprintf(s2,  "%08.3f",  5.);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_f_27) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%+8.3f",  (double)5);
s21_sprintf(s2,  "%+8.3f",  (double)5);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_f_28) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%+8f",  (double)5);
s21_sprintf(s2,  "%+8f",  (double)5);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_f_29) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "% f",  (double)5);
s21_sprintf(s2,  "% f",  (double)5);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_f_30) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "% +f",  (double)5);
s21_sprintf(s2,  "% +f",  (double)5);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_f_31) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "% -12f",  5.8);
s21_sprintf(s2,  "% -12f",  5.8);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_f_32) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "% +10f",  (double)5);
s21_sprintf(s2,  "% +10f",  (double)5);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_f_33) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "% -12.5f",  5.8);
s21_sprintf(s2,  "% -12.5f",  5.8);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_f_34) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1, "% 10f",  5.8);
s21_sprintf(s2, "% 10f",  5.8);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_f_35) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1, "%+-10f",  -5.8);
s21_sprintf(s2, "%+-10f",  -5.8);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_f_36) {
    char s1[100000]= "";
    char s2[100000]= "";
    sprintf(s1, "%lf",  9.8765);
    s21_sprintf(s2, "%lf",  9.8765);
    ck_assert_str_eq(s1,  s2);
} END_TEST

START_TEST(sprintf_f_37) {
    char s1[100000]= "";
    char s2[100000]= "";
    sprintf(s1, "%.14f",  9.8765);
    s21_sprintf(s2, "%.14f",  9.8765);
    ck_assert_str_eq(s1,  s2);
} END_TEST

START_TEST(sprintf_f_38) {
    char s1[100000]= "";
    char s2[100000]= "";
    sprintf(s1, "%.19f",  9.0);
    s21_sprintf(s2, "%.19f",  9.0);
    ck_assert_str_eq(s1,  s2);
} END_TEST

START_TEST(sprintf_f_39) {
    char s1[100000]= "";
    char s2[100000]= "";
    sprintf(s1, "%.12f",  -9.8765);
    s21_sprintf(s2, "%.12f",  -9.8765);
    ck_assert_str_eq(s1,  s2);
} END_TEST

START_TEST(sprintf_f_40) {
    char s1[100000]= "";
    char s2[100000]= "";
    sprintf(s1, "%.4f",  9.99999);
    s21_sprintf(s2, "%.4f",  9.99999);
    ck_assert_str_eq(s1,  s2);
} END_TEST

START_TEST(sprintf_f_41) {
    char s1[100000]= "";
    char s2[100000]= "";
    sprintf(s1, "% +5f",  9.55556);
    s21_sprintf(s2, "% +5f",  9.55556);
    ck_assert_str_eq(s1,  s2);
} END_TEST

START_TEST(sprintf_f_42) {
    char s1[100000]= "";
    char s2[100000]= "";
    sprintf(s1, "% 3f",  (double)0);
    s21_sprintf(s2, "% 3f",  (double)0);
    ck_assert_str_eq(s1,  s2);
} END_TEST

START_TEST(sprintf_f_43) {
    char s1[100000]= "";
    char s2[100000]= "";
    sprintf(s1, "% -+10f",  4.4);
    s21_sprintf(s2, "% -+10f",  4.4);
    ck_assert_str_eq(s1,  s2);
} END_TEST

START_TEST(sprintf_f_44) {
    char s1[100000]= "";
    char s2[100000]= "";
    sprintf(s1, "%.3f",  -4.99999);
    s21_sprintf(s2, "%.3f",  -4.99999);
    ck_assert_str_eq(s1,  s2);
} END_TEST

START_TEST(sprintf_s_14) {
    char s1[100]= "";
    char s2[100]= "";
    sprintf(s1,  "%10s %.16f %19s",  "Hello", 23.5, "World");
    s21_sprintf(s2,  "%10s %.16f %19s",  "Hello", 23.5, "World");
    ck_assert_str_eq(s1,  s2);
} END_TEST

START_TEST(sprintf_s_15) {
    char s1[100]= "";
    char s2[100]= "";
    sprintf(s1,  "%10.0s",  "Hello");
    s21_sprintf(s2,  "%10.0s",  "Hello");
    ck_assert_str_eq(s1,  s2);
} END_TEST

START_TEST(sprintf_s_16) {
    char s1[1000]= "";
    char s2[1000]= "";
    sprintf(s1,  "%210s",  "Hello");
    s21_sprintf(s2,  "%210s",  "Hello");
    ck_assert_str_eq(s1,  s2);
} END_TEST

START_TEST(int_ssprintf_c_8) {
char test_original[1024] = "";
char test_your[1024] = "";
ck_assert_int_eq(sprintf(test_original, "%5cHello %5c", \
    's', 'W'), s21_sprintf(test_your, "%5cHello %5c", 's', 'W'));
} END_TEST

START_TEST(sprintf_string_without_) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1, "faedhgadhsg %%");
s21_sprintf(s2, "faedhgadhsg %%");
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_s_1) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%s",  "Hello");
s21_sprintf(s2,  "%s",  "Hello");
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_s_2) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%.1s",  "Hello");
s21_sprintf(s2,  "%.1s",  "Hello");
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_s_3) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%-10s",  "Hello");
s21_sprintf(s2,  "%-10s",  "Hello");
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_s_4) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%.1s",  "Hello");
s21_sprintf(s2,  "%.1s",  "Hello");
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_s_5) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%s",  "Hello");
s21_sprintf(s2,  "%s",  "Hello");
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_s_6) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%s",  "");
s21_sprintf(s2,  "%s",  "");
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_s_7) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%s",  " ");
s21_sprintf(s2,  "%s",  " ");
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_s_8) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%-10s",  "Hello");
s21_sprintf(s2,  "%-10s",  "Hello");
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_s_9) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%s",  "Hello World");
s21_sprintf(s2,  "%s",  "Hello World");
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_s_10) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%s %s %.3s",  "HelloWorld",  "written",  "word");
s21_sprintf(s2,  "%s %s %.3s",  "HelloWorld",  "written",  "word");
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_s_11) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%s",  "testtest");
s21_sprintf(s2,  "%s",  "testtest");
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_s_12) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%s",  "test\ntest");
s21_sprintf(s2,  "%s",  "test\ntest");
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_s_13) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%10s",  "test\0test");
s21_sprintf(s2,  "%10s",  "test\0test");
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_s_18) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%-5.5s",  "AleAle");
s21_sprintf(s2,  "%-5.5s",  "AleAle");
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_s_19) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%5.5s",  "AleAle");
s21_sprintf(s2,  "%5.5s",  "AleAle");
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_u_1) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%02.5u%%\n",  (unsigned int)4);
s21_sprintf(s2,  "%02.5u%%\n",  (unsigned int)4);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_u_2) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%-10u%%\n",  (unsigned int)421);
s21_sprintf(s2,  "%-10u%%\n",  (unsigned int)421);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_u_3) {
char s1[100]= "";
char s2[100]= "";
short unsigned key_h = 421;
sprintf(s1,  "%-10hu%%\n",  key_h);
s21_sprintf(s2,  "%-10hu%%\n",  key_h);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_u_4) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%.5u%%\n",  (unsigned int)4);
s21_sprintf(s2,  "%.5u%%\n", (unsigned int)4);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_u_5) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%-10u%%\n",  (unsigned int)421);
s21_sprintf(s2,  "%-10u%%\n",  (unsigned int)421);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_u_6) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "max %u",  UINT_MAX);
s21_sprintf(s2,  "max %u",  UINT_MAX);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_u_7) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "min %u",  (unsigned int)0);
s21_sprintf(s2,  "min %u",  (unsigned int)0);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_u_8) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "Allo %u.%u%u%u",  (unsigned int)8,  (unsigned int)8,  (unsigned int)0,  (unsigned int)0);
s21_sprintf(s2,  "Allo %u.%u%u%u",  (unsigned int)8,  (unsigned int)8,  (unsigned int)0,  (unsigned int)0);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_u_9) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "Allo %u.%u%u, ,  %s%%",  (unsigned int)8,  (unsigned int)8,  (unsigned int)0,  "kek");
s21_sprintf(s2,  "Allo %u.%u%u, ,  %s%%",  (unsigned int)8,  (unsigned int)8,  (unsigned int)0,  "kek");
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_u_10) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%4u'",  (unsigned int)9);
s21_sprintf(s2,  "HHH '%4u'",  (unsigned int)9);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_u_11) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%4u'",  UINT_MAX);
s21_sprintf(s2,  "HHH '%4u'",  UINT_MAX);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_u_12) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%4u'",  (unsigned int)0);
s21_sprintf(s2,  "HHH '%4u'",  (unsigned int)0);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_u_13) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%.1u'",  (unsigned int)11);
s21_sprintf(s2,  "HHH '%.1u'",  (unsigned int)11);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_u_14) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%.1u'",  UINT_MAX);
s21_sprintf(s2,  "HHH '%.1u'",  UINT_MAX);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_u_15) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%.1u'",  (unsigned int)0);
s21_sprintf(s2,  "HHH '%.1u'",  (unsigned int)0);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_u_16) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%07u'",  (unsigned int)11);
s21_sprintf(s2,  "HHH '%07u'",  (unsigned int)11);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_u_17) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%07u'",  UINT_MAX);
s21_sprintf(s2,  "HHH '%07u'",  UINT_MAX);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_u_18) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%07u'",  (unsigned int)0);
s21_sprintf(s2,  "HHH '%07u'",  (unsigned int)0);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_u_19) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%-7u'",  (unsigned int)11);
s21_sprintf(s2,  "HHH '%-7u'",  (unsigned int)11);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_u_20) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%-7u'",  UINT_MAX);
s21_sprintf(s2,  "HHH '%-7u'",  UINT_MAX);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_u_21) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%-7u'",  (unsigned int)0);
s21_sprintf(s2,  "HHH '%-7u'", (unsigned int)0);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_u_22) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%15.5u'",  (unsigned int)93);
s21_sprintf(s2,  "HHH '%15.5u'",  (unsigned int)93);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_u_23) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%15.5u'",  UINT_MAX);
s21_sprintf(s2,  "HHH '%15.5u'",  UINT_MAX);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_u_24) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%15.5u'",  (unsigned int)0);
s21_sprintf(s2,  "HHH '%15.5u'",  (unsigned int)0);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_u_25) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%-20.1u'",  (unsigned int)29);
s21_sprintf(s2,  "HHH '%-20.1u'",  (unsigned int)29);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_u_26) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%-20.1u'",  UINT_MAX);
s21_sprintf(s2,  "HHH '%-20.1u'",  UINT_MAX);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_u_27) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%-20.1u'",  (unsigned int)0);
s21_sprintf(s2,  "HHH '%-20.1u'",  (unsigned int)0);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_h_1) {
char s1[100]= "";
char s2[100]= "";
short unsigned int key_h2 = 421;
sprintf(s1,  "%-10hu%%\n",  key_h2);
s21_sprintf(s2,  "%-10hu%%\n",  key_h2);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_h_2) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "ehehe '%4.3hi'",  (short int)57);
s21_sprintf(s2,  "ehehe '%4.3hi'",  (short int)57);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_h_3) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "ehehe '%-hi'",  (short int)5678);
s21_sprintf(s2,  "ehehe '%-hi'",  (short int)5678);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_h_4) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "ehehe '%+hi' Hello,  %s%c%c",  (short int)5678,  "Jon",  'n',  'y');
s21_sprintf(s2,  "ehehe '%+hi' Hello,  %s%c%c",  (short int)5678,  "Jon",  'n',  'y');
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_h_5) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "max %hd",  SHRT_MAX);
s21_sprintf(s2,  "max %hd",  SHRT_MAX);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_h_6) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "min %hd",  SHRT_MIN);
s21_sprintf(s2,  "min %hd",  SHRT_MIN);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_h_7) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%4hd'",  (short int)9);
s21_sprintf(s2,  "HHH '%4hd'",  (short int)9);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_h_8) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%9hd'",  SHRT_MAX);
s21_sprintf(s2,  "HHH '%9hd'",  SHRT_MAX);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_h_9) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%9hd'",  SHRT_MIN);
s21_sprintf(s2,  "HHH '%9hd'",  SHRT_MIN);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_h_10) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%.1hd'",  (short int)11);
s21_sprintf(s2,  "HHH '%.1hd'",  (short int)11);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_h_11) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%.1hd'",  SHRT_MAX);
s21_sprintf(s2,  "HHH '%.1hd'",  SHRT_MAX);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_h_12) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%.1hd'",  SHRT_MIN);
s21_sprintf(s2,  "HHH '%.1hd'",  SHRT_MIN);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_h_13) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%07hd'",  (short int)11);
s21_sprintf(s2,  "HHH '%07hd'",  (short int)11);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_h_14) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%07hd'",  SHRT_MAX);
s21_sprintf(s2,  "HHH '%07hd'",  SHRT_MAX);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_h_15) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%07hd'",  SHRT_MIN);
s21_sprintf(s2,  "HHH '%07hd'",  SHRT_MIN);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_h_16) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%-8hd'",  (short int)29);
s21_sprintf(s2,  "HHH '%-8hd'",  (short int)29);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_h_17) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%-8hd'",  SHRT_MAX);
s21_sprintf(s2,  "HHH '%-8hd'",  SHRT_MAX);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_h_18) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%-8hd'",  SHRT_MIN);
s21_sprintf(s2,  "HHH '%-8hd'",  SHRT_MIN);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_h_19) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%+6.3hd'",  (short int)84);
s21_sprintf(s2,  "HHH '%+6.3hd'",  (short int)84);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_h_20) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%+6.3hd'",  SHRT_MAX);
s21_sprintf(s2,  "HHH '%+6.3hd'",  SHRT_MAX);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_h_21) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%+6.3hd'",  SHRT_MIN);
s21_sprintf(s2,  "HHH '%+6.3hd'",  SHRT_MIN);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_h_22) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%.5hu%%\n",  (short unsigned int)4);
s21_sprintf(s2,  "%.5hu%%\n",  (short unsigned int)4);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_h_23) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%-10hu%%\n",  (short unsigned int)421);
s21_sprintf(s2,  "%-10hu%%\n",  (short unsigned int)421);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_h_24) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "max %hu",  USHRT_MAX);
s21_sprintf(s2,  "max %hu",  USHRT_MAX);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_h_25) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "min %hu",  (short unsigned int)0);
s21_sprintf(s2,  "min %hu",  (short unsigned int)0);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_h_26) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "Allo %hu.%hu%hu%hu",  (short unsigned int)8,  (short unsigned int)8,
(short unsigned int)0,  (short unsigned int)0);
s21_sprintf(s2,  "Allo %hu.%hu%hu%hu",  (short unsigned int)8,  (short unsigned int)8,
(short unsigned int)0,  (short unsigned int)0);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_h_27) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "Allo %hu.%hu%hu, ,  %s%%",  (short unsigned int)8,  (short unsigned int)8,
(short unsigned int)0,  "kek");
s21_sprintf(s2,  "Allo %hu.%hu%hu, ,  %s%%",  (short unsigned int)8,  (short unsigned int)8,
(short unsigned int)0,  "kek");
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_h_28) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%4hu'",  (short unsigned int)9);
s21_sprintf(s2,  "HHH '%4hu'",  (short unsigned int)9);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_h_29) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%4hu'",  USHRT_MAX);
s21_sprintf(s2,  "HHH '%4hu'",  USHRT_MAX);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_h_30) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%4hu'",  (short unsigned int)0);
s21_sprintf(s2,  "HHH '%4hu'",  (short unsigned int)0);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_h_31) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%.1hu'",  (short unsigned int)11);
s21_sprintf(s2,  "HHH '%.1hu'",  (short unsigned int)11);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_h_32) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%.1hu'",  USHRT_MAX);
s21_sprintf(s2,  "HHH '%.1hu'",  USHRT_MAX);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_h_33) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%.1hu'",  (short unsigned int)0);
s21_sprintf(s2,  "HHH '%.1hu'",  (short unsigned int)0);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_h_34) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%07hu'",  (short unsigned int)11);
s21_sprintf(s2,  "HHH '%07hu'",  (short unsigned int)11);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_h_35) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%07hu'",  USHRT_MAX);
s21_sprintf(s2,  "HHH '%07hu'",  USHRT_MAX);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_h_36) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%07hu'",  (short unsigned int)0);
s21_sprintf(s2,  "HHH '%07hu'",  (short unsigned int)0);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_h_37) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%-7hu'",  (short unsigned int)11);
s21_sprintf(s2,  "HHH '%-7hu'",  (short unsigned int)11);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_h_38) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%-7hu'",  USHRT_MAX);
s21_sprintf(s2,  "HHH '%-7hu'",  USHRT_MAX);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_h_39) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%-7hu'",  (short unsigned int)0);
s21_sprintf(s2,  "HHH '%-7hu'",  (short unsigned int)0);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_h_40) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%15.5hu'",  (short unsigned int)93);
s21_sprintf(s2,  "HHH '%15.5hu'",  (short unsigned int)93);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_h_41) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%15.5hu'",  USHRT_MAX);
s21_sprintf(s2,  "HHH '%15.5hu'",  USHRT_MAX);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_h_42) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%15.5hu'",  (short unsigned int)0);
s21_sprintf(s2,  "HHH '%15.5hu'",  (short unsigned int)0);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_h_43) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%-20.1hu'",  (short unsigned int)29);
s21_sprintf(s2,  "HHH '%-20.1hu'",  (short unsigned int)29);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_h_44) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%-20.1hu'",  USHRT_MAX);
s21_sprintf(s2,  "HHH '%-20.1hu'",  USHRT_MAX);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_h_45) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%-20.1hu'",  (short unsigned int)0);
s21_sprintf(s2,  "HHH '%-20.1hu'",  (short unsigned int)0);
ck_assert_str_eq(s1,  s2);

// l
}
END_TEST

START_TEST(sprintf_l_1) {
char s1[100]= "";
char s2[100]= "";
long unsigned int key_h1 = 421833526;
sprintf(s1,  "%-10lu%%\n",  key_h1);
s21_sprintf(s2,  "%-10lu%%\n",  key_h1);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_l_2) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "ehehe '%4.3li'",  42124224426);
s21_sprintf(s2,  "ehehe '%4.3li'",  42124224426);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_l_3) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "ehehe '%-li'",  7532223526);
s21_sprintf(s2,  "ehehe '%-li'",  7532223526);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_l_4) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "ehehe '%+li' Hello,  %s%c%c",  5622222227,  "Jon",  'n',  'y');
s21_sprintf(s2,  "ehehe '%+li' Hello,  %s%c%c",  5622222227,  "Jon",  'n',  'y');
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_l_5) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "max %ld",  LONG_MAX);
s21_sprintf(s2,  "max %ld",  LONG_MAX);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_l_6) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "min %ld",  LONG_MIN);
s21_sprintf(s2,  "min %ld",  LONG_MIN);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_l_7) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%4ld'",  92299993333);
s21_sprintf(s2,  "HHH '%4ld'",  92299993333);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_l_8) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%9ld'",  LONG_MAX);
s21_sprintf(s2,  "HHH '%9ld'",  LONG_MAX);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_l_9) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%9ld'",  LONG_MIN);
s21_sprintf(s2,  "HHH '%9ld'",  LONG_MIN);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_l_10) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%.1ld'",  11222222222);
s21_sprintf(s2,  "HHH '%.1ld'",  11222222222);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_l_11) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%.1ld'",  LONG_MAX);
s21_sprintf(s2,  "HHH '%.1ld'",  LONG_MAX);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_l_12) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%.1ld'",  LONG_MIN);
s21_sprintf(s2,  "HHH '%.1ld'",  LONG_MIN);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_l_13) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%07ld'",  1155555555555);
s21_sprintf(s2,  "HHH '%07ld'",  1155555555555);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_l_14) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%07ld'",  LONG_MAX);
s21_sprintf(s2,  "HHH '%07ld'",  LONG_MAX);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_l_15) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%07ld'",  LONG_MIN);
s21_sprintf(s2,  "HHH '%07ld'",  LONG_MIN);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_l_16) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%-8ld'",  2975222222222);
s21_sprintf(s2,  "HHH '%-8ld'",  2975222222222);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_l_17) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%-8ld'",  LONG_MAX);
s21_sprintf(s2,  "HHH '%-8ld'",  LONG_MAX);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_l_18) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%-8ld'",  LONG_MIN);
s21_sprintf(s2,  "HHH '%-8ld'",  LONG_MIN);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_l_19) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%+6.3ld'",  843441211111);
s21_sprintf(s2,  "HHH '%+6.3ld'",  843441211111);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_l_20) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%+6.3ld'",  LONG_MAX);
s21_sprintf(s2,  "HHH '%+6.3ld'",  LONG_MAX);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_l_21) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%+6.3ld'",  LONG_MIN);
s21_sprintf(s2,  "HHH '%+6.3ld'",  LONG_MIN);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_l_22) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%.5lu%%\n",  (long unsigned int)43445623111);
s21_sprintf(s2,  "%.5lu%%\n",  (long unsigned int)43445623111);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_l_23) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "%-10lu%%\n",  (long unsigned int)4211231245467546);
s21_sprintf(s2,  "%-10lu%%\n",  (long unsigned int)4211231245467546);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_l_24) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "max %lu",  ULONG_MAX);
s21_sprintf(s2,  "max %lu",  ULONG_MAX);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_l_25) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%4lu'",  (long unsigned int)92342214334);
s21_sprintf(s2,  "HHH '%4lu'",  (long unsigned int)92342214334);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_l_26) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%4lu'",  ULONG_MAX);
s21_sprintf(s2,  "HHH '%4lu'",  ULONG_MAX);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_l_27) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%.21lu'",  (long unsigned int)123423463451);
s21_sprintf(s2,  "HHH '%.21lu'",  (long unsigned int)123423463451);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_l_28) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%.21lu'",  ULONG_MAX);
s21_sprintf(s2,  "HHH '%.21lu'",  ULONG_MAX);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_l_29) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%022lu'",  (long unsigned int)123234545311);
s21_sprintf(s2,  "HHH '%022lu'",  (long unsigned int)123234545311);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_l_30) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%022lu'",  ULONG_MAX);
s21_sprintf(s2,  "HHH '%022lu'",  ULONG_MAX);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_l_31) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%-23lu'",  (long unsigned int)113452123543);
s21_sprintf(s2,  "HHH '%-23lu'",  (long unsigned int)113452123543);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_l_32) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%-23lu'",  ULONG_MAX);
s21_sprintf(s2,  "HHH '%-23lu'",  ULONG_MAX);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_l_33) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%15.5lu'",  (long unsigned int)9222228883);
s21_sprintf(s2,  "HHH '%15.5lu'",  (long unsigned int)9222228883);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_l_34) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%22.5lu'",  ULONG_MAX);
s21_sprintf(s2,  "HHH '%22.5lu'",  ULONG_MAX);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_l_35) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%-20.1lu'",  (long unsigned int)28888889999);
s21_sprintf(s2,  "HHH '%-20.1lu'",  (long unsigned int)28888889999);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_l_36) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "HHH '%-22.1lu'",  ULONG_MAX);
s21_sprintf(s2,  "HHH '%-22.1lu'",  ULONG_MAX);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(to_lower_1) {
char *s1 = s21_to_lower("WORLD");
char *s2 = "world";
ck_assert_str_eq(s1,  s2);
free(s1);
}
END_TEST

START_TEST(to_lower_2) {
char *s1 = s21_to_lower("incredible");
char *s2 = "incredible";
ck_assert_str_eq(s1,  s2);
free(s1);
}
END_TEST

START_TEST(to_lower_4) {
char *s1 = s21_to_lower("LIfe");
char *s2 = "life";
ck_assert_str_eq(s1,  s2);
free(s1);
}
END_TEST

START_TEST(to_lower_5) {
char *s1 = s21_to_lower("S21_scHool");
char *s2 = "s21_school";
ck_assert_str_eq(s1,  s2);
free(s1);
}
END_TEST

START_TEST(to_upper_1) {
char *s1 = s21_to_upper("world");
char *s2 = "WORLD";
ck_assert_str_eq(s1,  s2);
free(s1);
}
END_TEST

START_TEST(to_upper_2) {
char *s1 = s21_to_upper("INCREDIBLE");
char *s2 = "INCREDIBLE";
ck_assert_str_eq(s1,  s2);
free(s1);
}
END_TEST

START_TEST(to_upper_4) {
char *s1 = s21_to_upper("LIfe");
char *s2 = "LIFE";
ck_assert_str_eq(s1,  s2);
free(s1);
}
END_TEST

START_TEST(to_upper_5) {
char *s1 = s21_to_upper("S21_scHool");
char *s2 = "S21_SCHOOL";
ck_assert_str_eq(s1,  s2);
free(s1);
}
END_TEST

START_TEST(trim_1) {
char *s1 = s21_trim("world",  "w");
char *s2 = "orld";
ck_assert_str_eq(s1,  s2);
free(s1);
}
END_TEST

START_TEST(trim_2) {
char *s1 = s21_trim("  incredible  ",  " ");
char *s2 = "incredible";
ck_assert_str_eq(s1,  s2);
free(s1);
}
END_TEST

START_TEST(trim_4) {
char *s1 = s21_trim("0",  "trim");
char *s2 = "0";
ck_assert_str_eq(s1,  s2);
free(s1);
}
END_TEST

START_TEST(trim_5) {
char *s1 = s21_trim("1world4",  "14");
char *s2 = "world";
ck_assert_str_eq(s1,  s2);
free(s1);
}
END_TEST

START_TEST(insert_1) {
char *s1 = s21_insert("World",  "amazing",  1);
char *s2 = "Wamazingorld";
ck_assert_str_eq(s1,  s2);
free(s1);
}
END_TEST

START_TEST(insert_2) {
char *s1 = s21_insert("incredible",  "WIFE",  10);
char *s2 = "incredibleWIFE";
ck_assert_str_eq(s1,  s2);
free(s1);
}
END_TEST

START_TEST(insert_4) {
char *s1 = s21_insert("123",  "amazing",  3);
char *s2 = "123amazing";
ck_assert_str_eq(s1,  s2);
free(s1);
}
END_TEST

START_TEST(insert_5) {
char *s1 = s21_insert("0",  "NULLis",  0);
char *s2 = "NULLis0";
ck_assert_str_eq(s1,  s2);
free(s1);
}
END_TEST

START_TEST(insert_6) {
char *s1 = s21_insert("0123",  S21_NULL,  3);
char *s2 = "0123";
ck_assert_str_eq(s1,  s2);
free(s1);
}
END_TEST

START_TEST(sprintf_i_1) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "ehehe '%4.3i'",  57);
s21_sprintf(s2,  "ehehe '%4.3i'",  57);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_i_2) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "ehehe '%i'",  570097);
s21_sprintf(s2,  "ehehe '%i'",  570097);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_i_3) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "ehehe '%-10i'",  570097);
s21_sprintf(s2,  "ehehe '%-10i'",  570097);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_i_4) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "ehehe '%+10i'",  570097);
s21_sprintf(s2,  "ehehe '%+10i'",  570097);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_i_5) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "ehehe '% i'",  570097);
s21_sprintf(s2,  "ehehe '% i'",  570097);
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_i_6) {
char s1[100]= "";
char s2[100]= "";
sprintf(s1,  "ehehe '%+12i' Hello,  %s%c%c",  570097,  "Jon",  'n',  'y');
s21_sprintf(s2,  "ehehe '%+12i' Hello,  %s%c%c",  570097,  "Jon",  'n',  'y');
ck_assert_str_eq(s1,  s2);
}
END_TEST

START_TEST(sprintf_d_and_c_1) {
char test_original[1024] = "";
char test_your[1024] = "";
sprintf(test_original, "Hello %d %018d", 5, -23);
s21_sprintf(test_your, "Hello %d %018d", 5, -23);
ck_assert_str_eq(test_original, test_your);
} END_TEST

START_TEST(sprintf_2) {
char test_original[1024] = "";
char test_your[1024] = "";
sprintf(test_original, "Hello %s %f", "abc", -23.0);
s21_sprintf(test_your, "Hello %s %f", "abc", -23.0);
ck_assert_str_eq(test_original, test_your);
} END_TEST

START_TEST(sprintf_3) {
char test_original[1024] = "";
char test_your[1024] = "";
sprintf(test_original, "Hel%ulo %s %f", (unsigned int)100, "abc", -23.0);
s21_sprintf(test_your, "Hel%ulo %s %f", (unsigned int)100, "abc", -23.0);
ck_assert_str_eq(test_original, test_your);
} END_TEST

START_TEST(sprintf_pr_1) {
char test_original[1024] = "";
char test_your[1024] = "";
sprintf(test_original, "Hello %%");
s21_sprintf(test_your, "Hello %%");
ck_assert_str_eq(test_original, test_your);
} END_TEST

START_TEST(sprintf_pr_2) {
char test_original[1024] = "";
char test_your[1024] = "";
sprintf(test_original, "Hello 2022 World");
s21_sprintf(test_your, "Hello 2022 World");
ck_assert_str_eq(test_original, test_your);
} END_TEST

START_TEST(sprintf_c) {
char test_original[1024] = "";
char test_your[1024] = "";
sprintf(test_original, "Hello %c", 'W');
s21_sprintf(test_your, "Hello %c", 'W');
ck_assert_str_eq(test_original, test_your);
} END_TEST

START_TEST(s21_trim_20) {
char str1[] = "";
char str2[] = "jK";
char *str3 = s21_trim(str1, str2);
ck_assert_str_eq(str3, "");
free(str3);
} END_TEST

START_TEST(s21_trim_21) {
char str1[] = "sdfghjk";
char str2[] = " ";
char *str3 = s21_trim(str1, str2);
ck_assert_str_eq(str3, "sdfghjk");
free(str3);
} END_TEST

START_TEST(s21_trim_26) {
char str1[] = "   a231546yutiljkhgtyre565786oiu;jlkhb12         ";
char str2[] = "";
char *str3 = s21_trim(str1, str2);
ck_assert_str_eq(str3, "a231546yutiljkhgtyre565786oiu;jlkhb12");
free(str3);
} END_TEST

START_TEST(s21_trim_27) {
char str1[] = "   a231546yutiljkhgtyre565786oiu;jlkhb12         ";
char *str2 = S21_NULL;
char *str3 = s21_trim(str1, str2);
ck_assert_str_eq(str3, "a231546yutiljkhgtyre565786oiu;jlkhb12");
free(str3);
} END_TEST

START_TEST(s21_trim_28) {
char str1[] = "   a231546yutiljkhgtyre565786oiu;jlkhb12         ";
char *str2 = S21_NULL;
char *str3 = s21_trim(str1, str2);
ck_assert_str_eq(str3, "a231546yutiljkhgtyre565786oiu;jlkhb12");
free(str3);
} END_TEST

START_TEST(s21_trim_29) {
char str1[] = "   a231546yutiljkhgtyre565786oiu;jlkhb12         ";
char str2[4] = {0};
char *str3 = s21_trim(str1, str2);
ck_assert_str_eq(str3, "a231546yutiljkhgtyre565786oiu;jlkhb12");
free(str3);
} END_TEST

int main(void) {
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1,  tc1_1);
    tcase_add_test(tc1_1,  strchr_1);
    tcase_add_test(tc1_1,  strchr_2);
    tcase_add_test(tc1_1,  strchr_3);
    tcase_add_test(tc1_1,  strchr_4);
    tcase_add_test(tc1_1,  strchr_5);
    tcase_add_test(tc1_1,  strlen_1);
    tcase_add_test(tc1_1,  strlen_2);
    tcase_add_test(tc1_1,  strlen_3);
    tcase_add_test(tc1_1,  strlen_4);
    tcase_add_test(tc1_1,  strlen_5);
    tcase_add_test(tc1_1,  strlen_6);
    tcase_add_test(tc1_1,  memchr_1);
    tcase_add_test(tc1_1,  memchr_2);
    tcase_add_test(tc1_1,  memchr_3);
    tcase_add_test(tc1_1,  memchr_4);
    tcase_add_test(tc1_1,  memchr_5);
    tcase_add_test(tc1_1,  memchr_6);
    tcase_add_test(tc1_1,  memcmp_1);
    tcase_add_test(tc1_1,  memcmp_2);
    tcase_add_test(tc1_1,  memcmp_3);
    tcase_add_test(tc1_1,  memcmp_4);
    tcase_add_test(tc1_1,  memcmp_5);
    tcase_add_test(tc1_1,  memcmp_6);
    tcase_add_test(tc1_1,  strcat_1);
    tcase_add_test(tc1_1,  strcat_2);
    tcase_add_test(tc1_1,  strcat_3);
    tcase_add_test(tc1_1,  strcat_4);
    tcase_add_test(tc1_1,  strcat_5);
    tcase_add_test(tc1_1,  strcat_6);
    tcase_add_test(tc1_1,  strcmp_1);
    tcase_add_test(tc1_1,  strcmp_2);
    tcase_add_test(tc1_1,  strcmp_3);
    tcase_add_test(tc1_1,  strcmp_4);
    tcase_add_test(tc1_1,  strcmp_5);
    tcase_add_test(tc1_1,  strcmp_6);
    tcase_add_test(tc1_1,  strncmp_1);
    tcase_add_test(tc1_1,  strncmp_2);
    tcase_add_test(tc1_1,  strncmp_3);
    tcase_add_test(tc1_1,  strncmp_4);
    tcase_add_test(tc1_1,  strncmp_5);
    tcase_add_test(tc1_1,  strncat_1);
    tcase_add_test(tc1_1,  strncat_2);
    tcase_add_test(tc1_1,  strncat_3);
    tcase_add_test(tc1_1,  strncat_4);
    tcase_add_test(tc1_1,  strspn_1);
    tcase_add_test(tc1_1,  strspn_2);
    tcase_add_test(tc1_1,  strspn_3);
    tcase_add_test(tc1_1,  strspn_4);
    tcase_add_test(tc1_1,  strstr_1);
    tcase_add_test(tc1_1,  strstr_2);
    tcase_add_test(tc1_1,  strstr_3);
    tcase_add_test(tc1_1,  strstr_4);
    tcase_add_test(tc1_1,  strstr_5);
    tcase_add_test(tc1_1,  strrchr_1);
    tcase_add_test(tc1_1,  strrchr_2);
    tcase_add_test(tc1_1,  strrchr_3);
    tcase_add_test(tc1_1,  strcpy_1);
    tcase_add_test(tc1_1,  strcpy_2);
    tcase_add_test(tc1_1,  strcpy_3);
    tcase_add_test(tc1_1,  strncpy_1);
    tcase_add_test(tc1_1,  strncpy_2);
    tcase_add_test(tc1_1,  strncpy_3);
    tcase_add_test(tc1_1,  strncpy_4);
    tcase_add_test(tc1_1,  strpbrk_1);
    tcase_add_test(tc1_1,  strpbrk_2);
    tcase_add_test(tc1_1,  strpbrk_3);
    tcase_add_test(tc1_1,  strpbrk_4);
    tcase_add_test(tc1_1,  memset_1);
    tcase_add_test(tc1_1,  memset_2);
    tcase_add_test(tc1_1,  memset_3);
    tcase_add_test(tc1_1,  memset_4);
    tcase_add_test(tc1_1,  memcpy_1);
    tcase_add_test(tc1_1,  memcpy_2);
    tcase_add_test(tc1_1,  memcpy_3);
    tcase_add_test(tc1_1,  memcpy_4);
    tcase_add_test(tc1_1,  memmove_1);
    tcase_add_test(tc1_1,  memmove_2);
    tcase_add_test(tc1_1,  memmove_3);
    tcase_add_test(tc1_1,  memmove_4);
    tcase_add_test(tc1_1,  memmove_5);
    tcase_add_test(tc1_1,  memmove_6);
    tcase_add_test(tc1_1,  memmove_7);
    tcase_add_test(tc1_1,  strtok_1);
    tcase_add_test(tc1_1,  strtok_2);
    tcase_add_test(tc1_1,  strtok_3);
    tcase_add_test(tc1_1,  strtok_4);
    tcase_add_test(tc1_1,  strtok_6);
    tcase_add_test(tc1_1,  strtok_7);
    tcase_add_test(tc1_1,  strtok_8);
    tcase_add_test(tc1_1,  strtok_9);
    tcase_add_test(tc1_1,  strcspn_1);
    tcase_add_test(tc1_1,  strcspn_2);
    tcase_add_test(tc1_1,  strcspn_3);
    tcase_add_test(tc1_1,  strcspn_4);
    tcase_add_test(tc1_1,  strerror_1);
    tcase_add_test(tc1_1,  strerror_2);
    tcase_add_test(tc1_1,  strerror_3);
    tcase_add_test(tc1_1,  sprintf_c_1);
    tcase_add_test(tc1_1,  sprintf_c_2);
    tcase_add_test(tc1_1,  sprintf_c_3);
    tcase_add_test(tc1_1,  sprintf_c_4);
    tcase_add_test(tc1_1,  sprintf_c_5);
    tcase_add_test(tc1_1,  sprintf_c_6);
    tcase_add_test(tc1_1,  sprintf_c_7);
    tcase_add_test(tc1_1,  sprintf_c_8);
    tcase_add_test(tc1_1,  sprintf_c_9);
    tcase_add_test(tc1_1,  sprintf_c_10);
    tcase_add_test(tc1_1,  sprintf_d_1);
    tcase_add_test(tc1_1,  sprintf_d_2);
    tcase_add_test(tc1_1,  sprintf_d_3);
    tcase_add_test(tc1_1,  sprintf_d_4);
    tcase_add_test(tc1_1,  sprintf_d_5);
    tcase_add_test(tc1_1,  sprintf_d_6);
    tcase_add_test(tc1_1,  sprintf_d_7);
    tcase_add_test(tc1_1,  sprintf_d_8);
    tcase_add_test(tc1_1,  sprintf_d_9);
    tcase_add_test(tc1_1,  sprintf_d_10);
    tcase_add_test(tc1_1,  sprintf_d_12);
    tcase_add_test(tc1_1,  sprintf_d_13);
    tcase_add_test(tc1_1,  sprintf_d_14);
    tcase_add_test(tc1_1,  sprintf_d_15);
    tcase_add_test(tc1_1,  sprintf_d_16);
    tcase_add_test(tc1_1,  sprintf_d_17);
    tcase_add_test(tc1_1,  sprintf_d_18);
    tcase_add_test(tc1_1,  sprintf_d_19);
    tcase_add_test(tc1_1,  sprintf_d_20);
    tcase_add_test(tc1_1,  sprintf_d_21);
    tcase_add_test(tc1_1,  sprintf_d_22);
    tcase_add_test(tc1_1,  sprintf_d_23);
    tcase_add_test(tc1_1,  sprintf_d_24);
    tcase_add_test(tc1_1,  sprintf_d_25);
    tcase_add_test(tc1_1,  sprintf_d_26);
    tcase_add_test(tc1_1,  sprintf_d_27);
    tcase_add_test(tc1_1,  sprintf_d_28);
    tcase_add_test(tc1_1,  sprintf_d_29);
    tcase_add_test(tc1_1,  sprintf_d_30);
    tcase_add_test(tc1_1,  sprintf_d_31);
    tcase_add_test(tc1_1,  sprintf_d_32);
    tcase_add_test(tc1_1,  sprintf_d_33);
    tcase_add_test(tc1_1,  sprintf_d_34);
    tcase_add_test(tc1_1,  sprintf_proc);
    tcase_add_test(tc1_1,  sprintf_f_1);
    tcase_add_test(tc1_1,  sprintf_f_2);
    tcase_add_test(tc1_1,  sprintf_f_3);
    tcase_add_test(tc1_1,  sprintf_f_4);
    tcase_add_test(tc1_1,  sprintf_f_5);
    tcase_add_test(tc1_1,  sprintf_f_6);
    tcase_add_test(tc1_1,  sprintf_f_7);
    tcase_add_test(tc1_1,  sprintf_f_8);
    tcase_add_test(tc1_1,  sprintf_f_9);
    tcase_add_test(tc1_1,  sprintf_f_10);
    tcase_add_test(tc1_1,  sprintf_f_11);
    tcase_add_test(tc1_1,  sprintf_f_12);
    tcase_add_test(tc1_1,  sprintf_f_13);
    tcase_add_test(tc1_1,  sprintf_f_14);
    tcase_add_test(tc1_1,  sprintf_f_15);
    tcase_add_test(tc1_1,  sprintf_f_16);
    tcase_add_test(tc1_1,  sprintf_f_17);
    tcase_add_test(tc1_1,  sprintf_f_18);
    tcase_add_test(tc1_1,  sprintf_f_19);
    tcase_add_test(tc1_1,  sprintf_f_20);
    tcase_add_test(tc1_1,  sprintf_f_21);
    tcase_add_test(tc1_1,  sprintf_f_22);
    tcase_add_test(tc1_1,  sprintf_f_23);
    tcase_add_test(tc1_1,  sprintf_f_24);
    tcase_add_test(tc1_1,  sprintf_f_25);
    tcase_add_test(tc1_1,  sprintf_f_26);
    tcase_add_test(tc1_1,  sprintf_f_27);
    tcase_add_test(tc1_1,  sprintf_f_28);
    tcase_add_test(tc1_1,  sprintf_f_29);
    tcase_add_test(tc1_1,  sprintf_f_30);
    tcase_add_test(tc1_1,  sprintf_f_31);
    tcase_add_test(tc1_1,  sprintf_f_32);
    tcase_add_test(tc1_1,  sprintf_f_33);
    tcase_add_test(tc1_1,  sprintf_f_34);
    tcase_add_test(tc1_1,  sprintf_f_35);
    tcase_add_test(tc1_1,  sprintf_f_36);
    tcase_add_test(tc1_1,  sprintf_f_37);
    tcase_add_test(tc1_1,  sprintf_f_38);
    tcase_add_test(tc1_1,  sprintf_f_39);
    tcase_add_test(tc1_1,  sprintf_f_40);
    tcase_add_test(tc1_1,  sprintf_f_41);
    tcase_add_test(tc1_1,  sprintf_f_42);
    tcase_add_test(tc1_1,  sprintf_f_43);
    tcase_add_test(tc1_1,  sprintf_f_44);
    tcase_add_test(tc1_1,  sprintf_s_1);
    tcase_add_test(tc1_1,  sprintf_s_2);
    tcase_add_test(tc1_1,  sprintf_s_3);
    tcase_add_test(tc1_1,  sprintf_s_4);
    tcase_add_test(tc1_1,  sprintf_s_5);
    tcase_add_test(tc1_1,  sprintf_s_6);
    tcase_add_test(tc1_1,  sprintf_s_7);
    tcase_add_test(tc1_1,  sprintf_s_8);
    tcase_add_test(tc1_1,  sprintf_s_9);
    tcase_add_test(tc1_1,  sprintf_s_10);
    tcase_add_test(tc1_1,  sprintf_s_11);
    tcase_add_test(tc1_1,  sprintf_s_12);
    tcase_add_test(tc1_1,  sprintf_s_13);
    tcase_add_test(tc1_1,  sprintf_s_14);
    tcase_add_test(tc1_1,  sprintf_s_15);
    tcase_add_test(tc1_1,  sprintf_s_16);
    tcase_add_test(tc1_1,  sprintf_s_18);
    tcase_add_test(tc1_1,  sprintf_s_19);
    tcase_add_test(tc1_1,  sprintf_u_1);
    tcase_add_test(tc1_1,  sprintf_u_2);
    tcase_add_test(tc1_1,  sprintf_u_3);
    tcase_add_test(tc1_1,  sprintf_u_4);
    tcase_add_test(tc1_1,  sprintf_u_5);
    tcase_add_test(tc1_1,  sprintf_u_6);
    tcase_add_test(tc1_1,  sprintf_u_7);
    tcase_add_test(tc1_1,  sprintf_u_8);
    tcase_add_test(tc1_1,  sprintf_u_9);
    tcase_add_test(tc1_1,  sprintf_u_10);
    tcase_add_test(tc1_1,  sprintf_u_11);
    tcase_add_test(tc1_1,  sprintf_u_12);
    tcase_add_test(tc1_1,  sprintf_u_13);
    tcase_add_test(tc1_1,  sprintf_u_14);
    tcase_add_test(tc1_1,  sprintf_u_15);
    tcase_add_test(tc1_1,  sprintf_u_16);
    tcase_add_test(tc1_1,  sprintf_u_17);
    tcase_add_test(tc1_1,  sprintf_u_18);
    tcase_add_test(tc1_1,  sprintf_u_19);
    tcase_add_test(tc1_1,  sprintf_u_20);
    tcase_add_test(tc1_1,  sprintf_u_21);
    tcase_add_test(tc1_1,  sprintf_u_22);
    tcase_add_test(tc1_1,  sprintf_u_23);
    tcase_add_test(tc1_1,  sprintf_u_24);
    tcase_add_test(tc1_1,  sprintf_u_25);
    tcase_add_test(tc1_1,  sprintf_u_26);
    tcase_add_test(tc1_1,  sprintf_u_27);
    tcase_add_test(tc1_1,  sprintf_h_1);
    tcase_add_test(tc1_1,  sprintf_h_2);
    tcase_add_test(tc1_1,  sprintf_h_3);
    tcase_add_test(tc1_1,  sprintf_h_4);
    tcase_add_test(tc1_1,  sprintf_h_5);
    tcase_add_test(tc1_1,  sprintf_h_6);
    tcase_add_test(tc1_1,  sprintf_h_7);
    tcase_add_test(tc1_1,  sprintf_h_8);
    tcase_add_test(tc1_1,  sprintf_h_9);
    tcase_add_test(tc1_1,  sprintf_h_10);
    tcase_add_test(tc1_1,  sprintf_h_11);
    tcase_add_test(tc1_1,  sprintf_h_12);
    tcase_add_test(tc1_1,  sprintf_h_13);
    tcase_add_test(tc1_1,  sprintf_h_14);
    tcase_add_test(tc1_1,  sprintf_h_15);
    tcase_add_test(tc1_1,  sprintf_h_16);
    tcase_add_test(tc1_1,  sprintf_h_17);
    tcase_add_test(tc1_1,  sprintf_h_18);
    tcase_add_test(tc1_1,  sprintf_h_19);
    tcase_add_test(tc1_1,  sprintf_h_20);
    tcase_add_test(tc1_1,  sprintf_h_21);
    tcase_add_test(tc1_1,  sprintf_h_22);
    tcase_add_test(tc1_1,  sprintf_h_23);
    tcase_add_test(tc1_1,  sprintf_h_24);
    tcase_add_test(tc1_1,  sprintf_h_25);
    tcase_add_test(tc1_1,  sprintf_h_26);
    tcase_add_test(tc1_1,  sprintf_h_27);
    tcase_add_test(tc1_1,  sprintf_h_28);
    tcase_add_test(tc1_1,  sprintf_h_29);
    tcase_add_test(tc1_1,  sprintf_h_30);
    tcase_add_test(tc1_1,  sprintf_h_31);
    tcase_add_test(tc1_1,  sprintf_h_32);
    tcase_add_test(tc1_1,  sprintf_h_33);
    tcase_add_test(tc1_1,  sprintf_h_34);
    tcase_add_test(tc1_1,  sprintf_h_35);
    tcase_add_test(tc1_1,  sprintf_h_36);
    tcase_add_test(tc1_1,  sprintf_h_37);
    tcase_add_test(tc1_1,  sprintf_h_38);
    tcase_add_test(tc1_1,  sprintf_h_39);
    tcase_add_test(tc1_1,  sprintf_h_40);
    tcase_add_test(tc1_1,  sprintf_h_41);
    tcase_add_test(tc1_1,  sprintf_h_42);
    tcase_add_test(tc1_1,  sprintf_h_43);
    tcase_add_test(tc1_1,  sprintf_h_44);
    tcase_add_test(tc1_1,  sprintf_h_45);
    tcase_add_test(tc1_1,  sprintf_l_1);
    tcase_add_test(tc1_1,  sprintf_l_2);
    tcase_add_test(tc1_1,  sprintf_l_3);
    tcase_add_test(tc1_1,  sprintf_l_4);
    tcase_add_test(tc1_1,  sprintf_l_5);
    tcase_add_test(tc1_1,  sprintf_l_6);
    tcase_add_test(tc1_1,  sprintf_l_7);
    tcase_add_test(tc1_1,  sprintf_l_8);
    tcase_add_test(tc1_1,  sprintf_l_9);
    tcase_add_test(tc1_1,  sprintf_l_10);
    tcase_add_test(tc1_1,  sprintf_l_11);
    tcase_add_test(tc1_1,  sprintf_l_12);
    tcase_add_test(tc1_1,  sprintf_l_13);
    tcase_add_test(tc1_1,  sprintf_l_14);
    tcase_add_test(tc1_1,  sprintf_l_15);
    tcase_add_test(tc1_1,  sprintf_l_16);
    tcase_add_test(tc1_1,  sprintf_l_17);
    tcase_add_test(tc1_1,  sprintf_l_18);
    tcase_add_test(tc1_1,  sprintf_l_19);
    tcase_add_test(tc1_1,  sprintf_l_20);
    tcase_add_test(tc1_1,  sprintf_l_21);
    tcase_add_test(tc1_1,  sprintf_l_22);
    tcase_add_test(tc1_1,  sprintf_l_23);
    tcase_add_test(tc1_1,  sprintf_l_24);
    tcase_add_test(tc1_1,  sprintf_l_25);
    tcase_add_test(tc1_1,  sprintf_l_26);
    tcase_add_test(tc1_1,  sprintf_l_27);
    tcase_add_test(tc1_1,  sprintf_l_28);
    tcase_add_test(tc1_1,  sprintf_l_29);
    tcase_add_test(tc1_1,  sprintf_l_30);
    tcase_add_test(tc1_1,  sprintf_l_31);
    tcase_add_test(tc1_1,  sprintf_l_32);
    tcase_add_test(tc1_1,  sprintf_l_33);
    tcase_add_test(tc1_1,  sprintf_l_34);
    tcase_add_test(tc1_1,  sprintf_l_35);
    tcase_add_test(tc1_1,  sprintf_l_36);
    tcase_add_test(tc1_1,  to_lower_1);
    tcase_add_test(tc1_1,  to_lower_2);
    tcase_add_test(tc1_1,  to_lower_4);
    tcase_add_test(tc1_1,  to_lower_5);
    tcase_add_test(tc1_1,  to_upper_1);
    tcase_add_test(tc1_1,  to_upper_2);
    tcase_add_test(tc1_1,  to_upper_4);
    tcase_add_test(tc1_1,  to_upper_5);
    tcase_add_test(tc1_1,  trim_1);
    tcase_add_test(tc1_1,  trim_2);
    tcase_add_test(tc1_1,  trim_4);
    tcase_add_test(tc1_1,  trim_5);
    tcase_add_test(tc1_1,  insert_1);
    tcase_add_test(tc1_1,  insert_2);
    tcase_add_test(tc1_1,  insert_4);
    tcase_add_test(tc1_1,  insert_5);
    tcase_add_test(tc1_1,  insert_6);
    tcase_add_test(tc1_1,  sprintf_i_1);
    tcase_add_test(tc1_1,  sprintf_i_2);
    tcase_add_test(tc1_1,  sprintf_i_3);
    tcase_add_test(tc1_1,  sprintf_i_4);
    tcase_add_test(tc1_1,  sprintf_i_5);
    tcase_add_test(tc1_1,  sprintf_i_6);
    tcase_add_test(tc1_1,  sprintf_string_without_);
    tcase_add_test(tc1_1,  sprintf_d_and_c_1);
    tcase_add_test(tc1_1,  sprintf_2);
    tcase_add_test(tc1_1,  sprintf_3);
    tcase_add_test(tc1_1,  sprintf_pr_1);
    tcase_add_test(tc1_1,  sprintf_pr_2);
    tcase_add_test(tc1_1,  s21_trim_20);
    tcase_add_test(tc1_1,  s21_trim_21);
    tcase_add_test(tc1_1,  s21_trim_26);
    tcase_add_test(tc1_1,  s21_trim_27);
    tcase_add_test(tc1_1,  s21_trim_28);
    tcase_add_test(tc1_1,  s21_trim_29);
    tcase_add_test(tc1_1,  int_ssprintf_c_8);
    srunner_run_all(sr,  CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
